/***********************************************************************
  * Copyright (c) 2012, Baidu Inc. All rights reserved.
  * 
  * Licensed under the BSD License
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  * 
  *      license.txt
  *********************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bgcc_ServerInfo */

#ifndef _Included_bgcc_ServerInfo
#define _Included_bgcc_ServerInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bgcc_ServerInfo
 * Method:    create
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_bgcc_ServerInfo_create
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     bgcc_ServerInfo
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bgcc_ServerInfo_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
