/***********************************************************************
  * Copyright (c) 2012, Baidu Inc. All rights reserved.
  * 
  * Licensed under the BSD License
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  * 
  *      license.txt
  *********************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bgcc_Server */

#ifndef _Included_bgcc_Server
#define _Included_bgcc_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bgcc_Server
 * Method:    serve
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bgcc_Server_serve
  (JNIEnv *, jobject);

/*
 * Class:     bgcc_Server
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bgcc_Server_stop
  (JNIEnv *, jobject);

/*
 * Class:     bgcc_Server
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bgcc_Server_destroy
  (JNIEnv *, jobject);

/*
 * Class:     bgcc_Server
 * Method:    create
 * Signature: (Lbgcc/ServiceManager;Lbgcc/ThreadPool;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bgcc_Server_create
  (JNIEnv *, jobject, jobject, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
