/***********************************************************************
  * Copyright (c) 2012, Baidu Inc. All rights reserved.
  * 
  * Licensed under the BSD License
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  * 
  *      license.txt
  *********************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bgcc_ServiceManager */

#ifndef _Included_bgcc_ServiceManager
#define _Included_bgcc_ServiceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bgcc_ServiceManager
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bgcc_ServiceManager_create
  (JNIEnv *, jobject);

/*
 * Class:     bgcc_ServiceManager
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bgcc_ServiceManager_destroy
  (JNIEnv *, jobject);

/*
 * Class:     bgcc_ServiceManager
 * Method:    addService
 * Signature: (Lbgcc/Processor;)I
 */
JNIEXPORT jint JNICALL Java_bgcc_ServiceManager_addService
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
